//This file was autogenerated, please don't modify.
/*
 * Copyright (c) 2013. Rflect, Alex K.
 */


/**
 * @fileoverview DB interaction - calendar DAO.
 * @author alexeykofficial@gmail.com (Alex K.)
 */


exports.TARGETS = /*{TARGETS_JSON}*/[];